{% set version = "0.2.4" %}

package:
  name: aptools
  version: {{ version }}

source:
  url: https://github.com/AngelFP/APtools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d382b6700668194d099c014b63c8e6d34cf0cb26cccc0a85daeef8a5883de8d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - deprecated
    - h5py
    - numpy
    - openpmd-api
    - python >=3.6
    - scipy

test:
  imports:
    - aptools

about:
  home: https://github.com/AngelFP/APtools
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A collection of tools for accelerator physics

  description: |
    This package contains a set of tools to load and visualize the
    contents of a set of openPMD files (typically, a timeseries).
    The routines of openPMD-viewer can be used in two ways:
    (1) Use the Python API, in order to write a script that loads
        the data and produces a set of pre-defined plots.
    (2) Use the interactive GUI inside the Jupyter Notebook, in
        order to interactively visualize the data.
  dev_url: https://github.com/AngelFP/APtools

extra:
  recipe-maintainers:
    - AngelFP
    - ax3l
